### PR TITLE
Continue realtime video stream after socket reconnects

### PR DESCRIPTION
**Pull request by dborkan**
This pull request sets a 60 second (configurable) timer when it gets a reconnect_attempt event.  When that timer fires, video streaming is stopped.  If the socket successfully reconnects before the timer fires, the timer is cancelled, so that video streaming can resume.

Tested with corresponding server changes (https://github.com/igarape/copcast-server/pull/89) by starting video streaming, then putting my phone into airplane mode for less than 60 seconds, then taking my phone out of airplane mode.

### CODE REVIEW

**Comment by dborkan** [comment]
..need to make a few small changes on the server before this can be merged..

**Comment by brunosiqueira** [comment]
@dborkan I just tested the branch and I found some scenarios ( @martelli check this too) we must discuss:
- I streamed from a device to my local server. While streaming, I changed the device to airplane and back. The device turns off the streaming if there's no connection. The live streaming window remained open.
- I disabled the wifi from my computer and reactivated it in less than 2 minutes. I saw the speed up movement you mentioned, but after it, the video froze and I saw that it was turned off at the device.

I think it is much more a concept discussion than a bug itself:
- When streaming from the device to one single admin user and this user goes offline, should the device keep streaming for 2 minutes too before turning it off?
- in this scenario, where we wait for 2 minutes before disconnecting, the live streaming dialog stays open and frozen and the marker disappears right away. What should be the correct behavior here?
- if disconnected and the livestreaming dialog is open, should we show a notification in front of the window? Eg: "trying to buffer..."

**Comment by brunosiqueira** [comment]
@dborkan @martelli I was able to test successfully stoping the connection from both the app and admin.

But some questions remain:

- in this scenario, where we wait for 2 minutes before disconnecting, the live streaming dialog stays open and frozen and the marker disappears right away. What should be the correct behavior here?
if disconnected and the livestreaming dialog is open, should we show a notification in front of the window? Eg: "trying to buffer..."

**Comment by dborkan** [comment]
>
>
>    - I streamed from a device to my local server. While streaming, I
>    changed the device to airplane and back. The device turns off the streaming
>    if there's no connection. The live streaming window remained open.
>
> By saying "The device turns off the streaming if there's no connection",
do you mean it flips the "live streaming" switch we used to have?  With
this change, it should continue attempting to stream while the socket
reconnects, for up to a minute.

>
>    - I disabled the wifi from my computer and reactivated it in less than
>    2 minutes. I saw the speed up movement you mentioned, but after it, the
>    video froze and I saw that it was turned off at the device.
>
> I hadn't tested breaking the connection between the admin+server, only
between android+server.  I think reconnects between the android app and
server will be more common, but if we want to recover from admin-server
disconnects, we might want the same reconnect timeout logic for the admin
sockets as well.

>
>
> I think it is much more a concept discussion than a bug itself:
>
>    - When streaming from the device to one single admin user and this
>    user goes offline, should the device keep streaming for 2 minutes too
>    before turning it off?
>
> I believe this should be handled by the stopStreaming event sent over the
socket, which we control on the server.  I can check this again, but the
Android app should be able to distinguish between a temporary disconnect
between the android+server (reconnect_attempt) and an admin stopping the
stream

**Comment by brunosiqueira** [comment]
@dborkan please disregard that comment. I was testing with the wrong android branch (I merged your branchs with the webrecorder last version. It is working correctly, but I wonder if this might need to be improved:
- in this scenario, where we wait for 2 minutes before disconnecting, the live streaming dialog stays open and frozen and the marker disappears right away. What should be the correct behavior here? if disconnected and the livestreaming dialog is open, should we show a notification in front of the window? Eg: "trying to buffer..."

**Comment by dborkan** [comment]
Ah, OK.  For the new comment, what you describe is the current behavior,
but yes we could add some text here like "trying to buffer".  Do you think
this should be one of the bits of text that appears in the top right and
quickly disappears (like when a user flags an incident), or something in
the video window that remains until the connection resumes or the user
fully disconnects?

**Comment by dborkan** [comment]
Thanks, just FYI I've made a few more changes (not yet pushed) to the
copcast-server and copcast-admin code so that admins can be alerted when
users disconnect and reconnect.  I need to cleanup this code a tiny bit and
translate, but I will have pull requests for that today

**Pull request merged**
