### PR TITLE
Fixes for issues 

### PR DESCRIPTION
**Pull request by kamalg19**
Fixes done for below issues:
igarape/copcast-android#208
- Added new translations for android terms to Bulgarian.

igarape/copcast-android#199
- Addresses CC-01-002 Lack of Screenshot protections in Android App (Medium)
- Added screenshot protection to all activity.
- All activity onCreate() method now have getWindow().setFlags(LayoutParams.FLAG_SECURE, LayoutParams.FLAG_SECURE);

igarape/copcast-android#201
- Addresses CC-01-011 No Tapjacking protection installed for Android App (Medium)
- Added flag android:filterTouchesWhenObscured="true" of root view of all layout files.

igarape/copcast-server#103
- Addresses CC-01-010 Evidence tampering via video upload (Critical)
- To prevent timestamp manipulation via filename, checking that automatic date & time is enabled on device
- During app start, automatic date & time verified
- During app running, broadcast listener added to listen any changes done to change date/time/timezone

### CODE REVIEW

**Comment by brunosiqueira** [comment]
@kamalg19 regarding the network datetime validation for the upload, I would prefer if, instead of killing the application, it would block the upload  with the popup you created. Also, in the message, I don't think we should specify the path in the settings menu, since it can change depending on the device. You can use this message: "To upload data, DateTime must be set to "automatic."" - with the buttons config and cancel

**Comment by kamalg19** [comment]
@brunosiqueira Implemented review comments and added new commit to this pull request. Changes in this commit are:
igarape/copcast-server#103
- Addresses CC-01-010 Evidence tampering via video upload (Critical)
- Allow login even if date & time is not automatic
- Verify date & time is automatic, when user do following action:
a. start a mission
b. upload the video
c. reporting an incident
d. sending a incident form

**Comment by brunosiqueira** [comment]
Hey @kamalg19. This is looking really good. Still missing the same verification when registering incidents (in the method MainActitivity# onKeyLongPress()). Important since it attempts to start a mission if the app is IDLE. Let me know if you have any extra question.

**Comment by kamalg19** [comment]
@brunosiqueira Added date & time auto verification before registering incident. New commit added to this pull request.

**Pull request merged**
